# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e55de78afede0cb0e99009e57eff9696dbed986543ddc1ac526563200bacca9ac99d7fee8a2580c53d30393d3559da2de77a59c5ff4fa6a44b67abc752ff4c4b

test:
  secret_key_base: 92e7fed98b6f7909181a6280c4070d3fab7d9a98888d75aff66fc06d066a7617ac42a256f45452efac58fda978b65f8372e9a5753485f0366c2269f980a945ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
